# Generated by Django 4.2.3 on 2023-07-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default='undistinguished', max_length=100),
            preserve_default=False,
        ),
    ]
