# Generated by Django 4.2.3 on 2023-07-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='manual',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
