# Generated by Django 4.2.3 on 2023-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_material_pdf_alter_manual_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='material',
        ),
    ]
